### ISSUE TITLE
how do i do this? 

### ISSUE THREAD

**Issue by jerbearwright** [mborgerson/xsm64#2]
$ git am xsm64/patch/0001-xbox.patch
Committer identity unknown

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

**Comment by mborgerson** [comment]
Try running the commands that the error message tells you to

**Comment by jerbearwright** [comment]
sorry im a noob but i get what your saying

**Comment by jerbearwright** [comment]
$ git am xsm64/patch/0001-xbox.patch
Applying: xbox
error: patch failed: Makefile:112
error: Makefile: patch does not apply
error: patch failed: src/pc/pc_main.c:36
error: src/pc/pc_main.c: patch does not apply
Patch failed at 0001 xbox
hint: Use 'git am --show-current-patch=diff' to see the failed patch
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".

jerem@DESKTOP-U1TTTST MINGW64 ~/sm64-port
$ git am --show-current-patch=diff
---
 Makefile                                   | 62 ++++++++++++++++++++--
 include/PR/os_libc.h                       |  6 +++
 src/engine/math_util.h                     |  5 ++
 src/game/paintings.c                       |  1 +
 src/pc/audio/audio_sdl.c                   |  4 +-
 src/pc/audio/audio_wasapi.cpp              |  2 +-
 src/pc/audio/audio_wasapi.h                |  2 +-
 src/pc/controller/controller_entry_point.c |  4 +-
 src/pc/controller/controller_sdl.c         | 11 +++-
 src/pc/controller/controller_xinput.c      |  2 +-
 src/pc/controller/controller_xinput.h      |  2 +-
 src/pc/controller/wup.c                    |  2 +-
 src/pc/dlmalloc.c                          |  2 +-
 src/pc/gfx/gfx_pc.c                        |  6 +++
 src/pc/pc_main.c                           | 28 +++++++++-
 src/pc/ultra_reimplementation.c            | 12 +++++
 16 files changed, 135 insertions(+), 16 deletions(-)

diff --git a/Makefile b/Makefile
index ab0dff3..b6c6847 100644
--- a/Makefile
+++ b/Makefile
@@ -32,3 +32,8 @@ ifeq ($(TARGET_N64),0)
   TARGET_WINDOWS := 0
-  ifeq ($(TARGET_WEB),0)
:

**Comment by mborgerson** [comment]
Looks like you're applying the patches to the wrong source repo, see https://github.com/mborgerson/xsm64/issues/1 or you just need to check out the right source version. Sometime around October 2020 should apply

**Comment by jerbearwright** [comment]
this is the repo command im using this isnt right? 

git clone https://github.com/sm64-port/sm64-port.git

**Comment by jerbearwright** [comment]
jerem@DESKTOP-U1TTTST MINGW64 ~
# git clone 'https://github.com/sm64-port/sm64-port.git'
Cloning into 'sm64-port'...
remote: Enumerating objects: 12905, done.
remote: Total 12905 (delta 0), reused 0 (delta 0), pack-reused 12905
Receiving objects: 100% (12905/12905), 18.68 MiB | 1.19 MiB/s, done.
Resolving deltas: 100% (5693/5693), done.
Updating files: 100% (3227/3227), done.

jerem@DESKTOP-U1TTTST MINGW64 ~
# cd sm64-port

jerem@DESKTOP-U1TTTST MINGW64 ~/sm64-port
# git clone'https://github.com/mborgerson/xsm64.git'
git: 'clonehttps://github.com/mborgerson/xsm64.git' is not a git command. See 'git --help'.

jerem@DESKTOP-U1TTTST MINGW64 ~/sm64-port
# git clone 'https://github.com/mborgerson/xsm64.git' xsm64
Cloning into 'xsm64'...
remote: Enumerating objects: 44, done.
remote: Counting objects: 100% (44/44), done.
remote: Compressing objects: 100% (33/33), done.
remote: Total 44 (delta 8), reused 35 (delta 5), pack-reused 0
Receiving objects: 100% (44/44), 18.64 KiB | 867.00 KiB/s, done.
Resolving deltas: 100% (8/8), done.

jerem@DESKTOP-U1TTTST MINGW64 ~/sm64-port
# git am xsm64/patch/0001-xbox.patch

Applying: xbox
error: patch failed: Makefile:112
error: Makefile: patch does not apply
error: patch failed: src/pc/pc_main.c:36
error: src/pc/pc_main.c: patch does not apply
Patch failed at 0001 xbox
hint: Use 'git am --show-current-patch=diff' to see the failed patch
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".

**Comment by jerbearwright** [comment]
ive been able to get to the last command to build the .xbe but this happens, what am i missing/doing wrong?  

C:/msys64/mingw64/include/c++/13.1.0/bits/stl_function.h:117:12: note: declared here
  117 |     struct unary_function
      |            ^~~~~~~~~~~~~~
patch_libultra_math.c: In function 'main':
patch_libultra_math.c:113:26: warning: overflow in conversion from 'long long unsigned int' to 'long
 int' changes value from '18446744073709551564' to '-52' [-Woverflow]
  113 |                 fseek(f, -sizeof(hdr), SEEK_CUR);
      |                          ^~~~~~~~~~~~
Makefile:584: warning: overriding recipe for target 'clean'
/home/jerem/sm64-port/nxdk//Makefile:179: warning: ignoring old recipe for target 'clean'
Makefile:587: warning: overriding recipe for target 'distclean'
/home/jerem/sm64-port/nxdk//Makefile:186: warning: ignoring old recipe for target 'distclean'
cpp -P -DVERSION_US -I . -o build/us_pc/level_rules.mk levels/level_rules.mk
Makefile:584: warning: overriding recipe for target 'clean'
/home/jerem/sm64-port/nxdk//Makefile:179: warning: ignoring old recipe for target 'clean'
Makefile:587: warning: overriding recipe for target 'distclean'
/home/jerem/sm64-port/nxdk//Makefile:186: warning: ignoring old recipe for target 'distclean'
[ CC       ] /home/jerem/sm64-port/nxdk//lib/pdclib/functions/ctype/isalnum.obj
C:/msys64/home/jerem/sm64-port/nxdk/lib/pdclib/functions/ctype/isalnum.c:13:5: warning: 'isalnum'
      redeclared without 'dllimport' attribute: previous 'dllimport' ignored
      [-Winconsistent-dllimport]
int isalnum( int c )
    ^
C:/msys64/mingw64/include/ctype.h:124:23: note: previous declaration is here
  _CRTIMP int __cdecl isalnum(int _C);
                      ^
C:/msys64/mingw64/include/ctype.h:124:3: note: previous attribute is here
  _CRTIMP int __cdecl isalnum(int _C);
  ^
C:/msys64/mingw64/include/_mingw.h:52:40: note: expanded from macro '_CRTIMP'
#      define _CRTIMP  __attribute__ ((__dllimport__))
                                       ^
1 warning generated.
[ CC       ] /home/jerem/sm64-port/nxdk//lib/pdclib/functions/ctype/isalpha.obj
C:/msys64/home/jerem/sm64-port/nxdk/lib/pdclib/functions/ctype/isalpha.c:13:5: warning: 'isalpha'
      redeclared without 'dllimport' attribute: previous 'dllimport' ignored
      [-Winconsistent-dllimport]
int isalpha( int c )
    ^
C:/msys64/mingw64/include/ctype.h:110:23: note: previous declaration is here
  _CRTIMP int __cdecl isalpha(int _C);
                      ^
C:/msys64/mingw64/include/ctype.h:110:3: note: previous attribute is here
  _CRTIMP int __cdecl isalpha(int _C);
  ^
C:/msys64/mingw64/include/_mingw.h:52:40: note: expanded from macro '_CRTIMP'
#      define _CRTIMP  __attribute__ ((__dllimport__))
                                       ^
C:/msys64/home/jerem/sm64-port/nxdk/lib/pdclib/functions/ctype/isalpha.c:15:14: error: use of
      undeclared identifier '_PDCLIB_lc_ctype'
    return ( _PDCLIB_lc_ctype.entry[c].flags & _PDCLIB_CTYPE_ALPHA );
             ^
C:/msys64/home/jerem/sm64-port/nxdk/lib/pdclib/functions/ctype/isalpha.c:15:48: error: use of
      undeclared identifier '_PDCLIB_CTYPE_ALPHA'
    return ( _PDCLIB_lc_ctype.entry[c].flags & _PDCLIB_CTYPE_ALPHA );
                                               ^
1 warning and 2 errors generated.
make: *** [/home/jerem/sm64-port/nxdk//Makefile:133: /home/jerem/sm64-port/nxdk//lib/pdclib/functions/ctype/isalpha.obj] Error 1
